version: '3'
services:
  proto:
    command: ./proto/protoc.sh
    build: ./proto
    volumes:
      - .:/proto
  server:
    build: ./server
    volumes:
      - ./server:/go/src/grpc-web-chat
    ports:
      - "9090:9090"
    depends_on:
      - proto
  envoy:
    build: ./proxy
    ports:
      - "8081:8081"
    links:
      - server
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - proto
    ports:
      - "8080:8080"