version: '3'
services:
  proto:
    command: ./proto/protoc.sh
    build:
      context: .
      dockerfile: ./proto/Dockerfile
    volumes:
      - .:/proto
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/go/src/grpc-web-chat
    ports:
      - "9090:9090"
    depends_on:
      - proto